### ISSUE TITLE
Suggestion: Adding Support for BadgeDB

### ISSUE THREAD

**Issue by de-katze** [HypedDomi/ClientModBadges-API#1]
simply as title says, BadgeDB support.

API Endpoints
https://badgedb.katze.click/api/badge/user?id=${userid}
```json
{
    "image": "discord cdn image link, required",
    "description": "badge tooltip/name, optional"
}
```

https://badgedb.katze.click/api/badge/get
```json
[
    array of objects specified above for every user
]

**Comment by de-katze** [comment]
The user will be getting a slight apo change later today
It will have a key, "success" of true or false whether the user exist or not.

**Comment by HypedDomi** [comment]
Does your API require specific Headers? Because right now I'm getting hitting the timeout every time
```js
const resp = await axios.get(`https://badgedb.katze.click/api/badge/user?id=${userId}`, { headers: { "Cache-Control": "no-cache" }, timeout: 5000 });
```
<img width="321" alt="image" src="https://github.com/HypedDomi/ClientModBadges-API/assets/50876016/df915608-db8c-4ed2-ae2e-fa1045c0a4a1">

**Comment by de-katze** [comment]
It should jot require any special headers.
Are you able to do any further debugging?

**Comment by HypedDomi** [comment]
I can later try to test it on my server rather than my Mac

**Comment by HypedDomi** [comment]
Somehow it fixed itself. I'll merge the PR
